# Generated by Django 4.2.29 on 2026-04-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medium', models.CharField(choices=[('oil', 'Oil'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('mixed', 'Mixed Media'), ('other', 'Other')], max_length=20)),
                ('size', models.CharField(max_length=100)),
                ('year_created', models.PositiveIntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='artworks/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork')),
            ],
        ),
    ]
