# Generated by Django 6.0.3 on 2026-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_certificate_certificate_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
                ('description', models.TextField()),
                ('curator_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artworks', models.ManyToManyField(blank=True, related_name='exhibitions', to='artworks.artwork')),
            ],
            options={
                'ordering': ['-featured', '-start_date', 'title'],
            },
        ),
    ]
