# Generated by Django 6.0.3 on 2026-06-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_exhibition_artists(apps, schema_editor):
    Exhibition = apps.get_model('artworks', 'Exhibition')
    Profile = apps.get_model('accounts', 'Profile')
    fallback_artist_id = Profile.objects.filter(user_type='artist').values_list('user_id', flat=True).first()
    for exhibition in Exhibition.objects.all():
        artwork = exhibition.artworks.first()
        if artwork:
            exhibition.artist_id = artwork.artist_id
        elif fallback_artist_id:
            exhibition.artist_id = fallback_artist_id
        if not exhibition.curator_statement and exhibition.description:
            exhibition.curator_statement = exhibition.description
        exhibition.visibility = 'published'
        exhibition.save(update_fields=['artist_id', 'curator_statement', 'visibility'])
    Exhibition.objects.filter(artist__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_exhibition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='artist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exhibitions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='curator_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='exhibitions/featured/'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='visibility',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('published', 'Published')],
                default='draft',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='curator_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(assign_exhibition_artists, migrations.RunPython.noop),
    ]
