# Generated by Django 6.0.3 on 2026-06-13 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomArtworkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=150)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_whatsapp', models.CharField(blank=True, max_length=30)),
                ('artwork_type', models.CharField(choices=[('portrait', 'Portrait'), ('family_portrait', 'Family Portrait'), ('pet_portrait', 'Pet Portrait'), ('landscape', 'Landscape'), ('abstract', 'Abstract'), ('character_art', 'Character Art'), ('other', 'Other')], max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom_requests/')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_artwork_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
